<?php
//<Konfigurationsabschnitt>
define("EZSQL_DB_USER", "esniper");
define("EZSQL_DB_PASSWORD", "esniper");
define("EZSQL_DB_NAME", "esniper");
define("EZSQL_DB_HOST", "linux.home");
define("PATH_TO_ESNIPER", "/usr/bin/esniper"); //Pfad zu esniper inkl. Dateiname
define("PATH_TO_ESNIPERCONFIG", "/opt/esniper/config"); //Pfad zur esniper config inkl. Dateiname
define("TMP_FOLDER","/tmp"); //Pfad zum temporären Ordner
//German 1
define("LANG",1);
//English 2
//</Konfigurationsabschnitt>
?>